---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-workspace-controller-view-all
subjects:
- kind: ServiceAccount
  name: che-workspace-controller
  namespace: che-workspace-controller
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-workspace-controller
subjects:
- kind: ServiceAccount
  name: che-workspace-controller
  namespace: che-workspace-controller
roleRef:
  kind: ClusterRole
  name: che-workspace-controller
  apiGroup: rbac.authorization.k8s.io
