apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: che-workspace-operator
  template:
    metadata:
      labels:
        name: che-workspace-operator
    spec:
      serviceAccountName: che-workspace-operator
      containers:
        - name: che-workspace-operator
          # Replace this with the built image name
          image: quay.io/che-incubator/che-workspace-controller:nightly
          command:
          - che-workspace-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-operator"
          ports:
            - name: webhook-server
              containerPort: 8443
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: che-workspace-controller
  name: workspace-controller
spec:
  ports:
    - targetPort: webhook-server
      protocol: TCP
      port: 443
  selector:
    name: che-workspace-operator